"""Add pdb_id to Protein model

Revision ID: f063b3e674b5
Revises: 
Create Date: 2025-07-02 12:14:31.572172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f063b3e674b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proteins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdb_id', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proteins', schema=None) as batch_op:
        batch_op.drop_column('pdb_id')

    # ### end Alembic commands ###
